const SET_USER = 'SET_USER';
const GET_ALL_WATER = 'GET_ALL_WATER';
const GET_WATER = 'GET_WATER';
const UPDATE_WATER = 'UPDATE_WATER';
const PROGRESS_CALCULATON = 'PROGRESS_CALCULATION';
const ALL_WATER_ERRORS = 'ALL_WATER_ERRORS';
const ADD_ALL_WATER = 'ADD_ALL_WATER';
